function tab = etAoI_prepareCoreVariables(tab)

    wantedVars = {...
        'propVal'                ,...
        'totalScreenWatchTime'   ,...
        '*_numLooks'             ,...
        '*_meanLook'             ,...
        '*_peakLook'             ,...
        '*_minLook'              ,...
        '*_propInAOI'            ,...
        '*_firstTimeS'           ,...
        '*_meanDistance'         ,...
        '*_ratioInAOI'           ,...
        'id'                     ,...
        'wave'                   ,...
        'include'                ,...
        'task'                   ,...
        };
    tab = filterTableVariables(tab, wantedVars);
    tab = tab(tab.include, :);

end